environment_variables:
  MY_CUSTOM_ENV_VAR: "custom_value"
general_settings:
  master_key: sk-master-key
  database_url: postgresql://postgres:postgres@127.0.0.1:5432/litellm
model_list:
  - model_name: imagen-3.0-generate-001
    litellm_params:
        model: vertex_ai/imagen-3.0-generate-001
  - model_name: gemini-3-pro-preview
    litellm_params:
        model: vertex_ai/gemini-3-pro-preview
  - model_name: gemini-2.5-flash
    litellm_params:
        model: vertex_ai/gemini-2.5-flash

litellm_settings:

  callbacks: custom_callbacks.proxy_handler_instance # sets litellm.callbacks = [proxy_handler_instance]

  key_generation_settings:
    team_key_generation:
      allowed_team_member_roles: ["admin"]
      required_params: ["tags"] # require team admins to set tags for cost-tracking when generating a team key
    personal_key_generation: # maps to 'Default Team' on UI 
      allowed_user_roles: ["proxy_admin"]


# sk-GTbdyKC-aB12w1eHo3x2HQ